import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Login from './login'
import Card from  "./components/Card"
import cookie from 'cookie'

export default function Home(place) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col justify-center items-center w-full h-full'>
        {
          cookie.name === 'KDV' ? <p> Well come </p> :  <Login />
        } 
        
      
        
      </main>
    </div>
  )
}




